/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AtomThemeToggle: typeof import('./src/components/atoms/AtomThemeToggle/AtomThemeToggle.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    DefaultTemplate: typeof import('./src/components/templates/DefaultTemplate/DefaultTemplate.vue')['default']
    OrganismFooter: typeof import('./src/components/organisms/OrganismFooter/OrganismFooter.vue')['default']
    OrganismHeader: typeof import('./src/components/organisms/OrganismHeader/OrganismHeader.vue')['default']
    Organisms: typeof import('./src/components/organisms/Organisms/Organisms.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemplateDefault: typeof import('./src/components/templates/TemplateDefault/TemplateDefault.vue')['default']
    ThemeToggle: typeof import('./src/components/atoms/ThemeToggle/ThemeToggle.vue')['default']
  }
}
