/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/ui/accordion/Accordion.vue')['default']
    AccordionContent: typeof import('./src/components/ui/accordion/AccordionContent.vue')['default']
    AccordionItem: typeof import('./src/components/ui/accordion/AccordionItem.vue')['default']
    AccordionTrigger: typeof import('./src/components/ui/accordion/AccordionTrigger.vue')['default']
    AtomLazyImage: typeof import('./src/components/atoms/AtomLazyImage/AtomLazyImage.vue')['default']
    AtomThemeToggle: typeof import('./src/components/atoms/AtomThemeToggle/AtomThemeToggle.vue')['default']
    Badge: typeof import('./src/components/ui/badge/Badge.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    Drawer: typeof import('./src/components/ui/drawer/Drawer.vue')['default']
    DrawerContent: typeof import('./src/components/ui/drawer/DrawerContent.vue')['default']
    DrawerDescription: typeof import('./src/components/ui/drawer/DrawerDescription.vue')['default']
    DrawerFooter: typeof import('./src/components/ui/drawer/DrawerFooter.vue')['default']
    DrawerHeader: typeof import('./src/components/ui/drawer/DrawerHeader.vue')['default']
    DrawerOverlay: typeof import('./src/components/ui/drawer/DrawerOverlay.vue')['default']
    DrawerTitle: typeof import('./src/components/ui/drawer/DrawerTitle.vue')['default']
    FormControl: typeof import('./src/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./src/components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./src/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./src/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./src/components/ui/form/FormMessage.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    MoleculeQuestionItem: typeof import('./src/components/molecules/MoleculeQuestionItem/MoleculeQuestionItem.vue')['default']
    MoleculeQuizHeader: typeof import('./src/components/molecules/MoleculeQuizHeader/MoleculeQuizHeader.vue')['default']
    MoleculeScoreDrawer: typeof import('./src/components/molecules/MoleculeScoreDrawer/MoleculeScoreDrawer.vue')['default']
    OrganismApplicationSetting: typeof import('./src/components/organisms/OrganismApplicationSetting/OrganismApplicationSetting.vue')['default']
    OrganismFooter: typeof import('./src/components/organisms/OrganismFooter/OrganismFooter.vue')['default']
    OrganismHeader: typeof import('./src/components/organisms/OrganismHeader/OrganismHeader.vue')['default']
    OrganismQuiz: typeof import('./src/components/organisms/OrganismQuiz/OrganismQuiz.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./src/components/ui/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./src/components/ui/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./src/components/ui/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./src/components/ui/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./src/components/ui/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./src/components/ui/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./src/components/ui/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./src/components/ui/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./src/components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./src/components/ui/select/SelectValue.vue')['default']
    TemplateDefault: typeof import('./src/components/templates/TemplateDefault/TemplateDefault.vue')['default']
  }
}
